/**
 * README / Pages screenshots, regenerated by .github/workflows/visual-docs.yml.
 *
 *   npx playwright test --config config/playwright.visual-docs.config.ts
 *
 * Backend-free: every /api call is mocked with fictional demo data and the
 * clock is frozen, so the output only changes when the UI does. Each file is
 * named after its feature id in promo/spots.json (docs/screenshots/<id>.png).
 */
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test, expect } from '@playwright/test';
import type { Locator, Page } from '@playwright/test';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const PLATFORM_BASE = 'http://127.0.0.1:3001';
const NOW = new Date('2027-01-15T15:00:00Z');

// Written through toHaveScreenshot (snapshotPathTemplate -> docs/screenshots,
// updateSnapshots: 'changed'), so a file is only rewritten when the UI really
// changed, not for one-level antialiasing noise between runs.
const shot = (target: Page | Locator, id: string) => expect(target).toHaveScreenshot(`${id}.png`);
const json = (body: unknown, status = 200) => ({ status, contentType: 'application/json', body: JSON.stringify(body) });

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(NOW);
  // The hero video would make the frame depend on decode timing; its poster
  // (the same shot) shows instead.
  await page.route(/\.(mp4|mov|webm)(\?.*)?$/, (route) => route.abort());
});

const settle = async (page: Page) => {
  await page.evaluate(() => document.fonts.ready);
  await page.waitForFunction(() => Array.from(document.images).filter((i) => i.loading !== 'lazy').every((i) => i.complete));
};

const sectionShot = async (page: Page, selector: string, id: string) => {
  const section = page.locator(selector);
  await section.scrollIntoViewIfNeeded();
  await page.waitForFunction((sel) => Array.from(document.querySelectorAll(`${sel} img`)).every((i) => (i as HTMLImageElement).complete), selector);
  await page.waitForTimeout(900); // scroll-reveal transitions
  // The fixed nav would sit on top of the section's heading.
  await page.addStyleTag({ content: 'header, .navbar { visibility: hidden !important; }' });
  await shot(section, id);
};

test.describe('marketing site', () => {
  test('immersive-hero-section', async ({ page }) => {
    await page.goto('/');
    await settle(page);
    // The cursor-follow drone hovers up-and-right of the pointer with a beam back to it.
    // One move only: the drone eases to a stop frame by frame, so a single
    // target gives the same resting position every run.
    await page.mouse.move(880, 660);
    await expect(page.locator('.cursor-drone')).toHaveClass(/is-visible/);
    await page.waitForTimeout(2500);
    await shot(page, 'immersive-hero-section');
  });

  test('service-packages', async ({ page }) => {
    await page.goto('/');
    await settle(page);
    await sectionShot(page, '#services', 'service-packages');
  });

  test('dynamic-gallery', async ({ page }) => {
    await page.goto('/');
    await settle(page);
    await expect(page.locator('.gallery-item').first()).toBeVisible();
    await sectionShot(page, '#gallery', 'dynamic-gallery');
  });

  test('responsive-design', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    await settle(page);
    await page.waitForTimeout(600);
    await shot(page, 'responsive-design');
  });

  // campaign-personalization has no screenshot yet: scripts/campaign.js targets
  // `.hero-subline`, which index.html doesn't have, so the variant never renders.

  test('local-dashboard', async ({ page }) => {
    await page.addInitScript((updatedAt) => {
      const totals = { landing_view: 412, gallery_engagement: 187, booking_cta_click: 64, contact_submit: 21, service_interest: 96 };
      const events = [
        { name: 'booking_cta_click', at: updatedAt, metadata: { source: 'instagram', location: 'hero' } },
        { name: 'gallery_engagement', at: updatedAt, metadata: { source: 'google', target: 'sunset-marina' } },
      ];
      localStorage.setItem('skyview:conversion-metrics:v1', JSON.stringify({ version: 1, updatedAt, totals, events }));
      sessionStorage.setItem('skyview:landing-view-recorded:v1', '1');
    }, NOW.toISOString());
    // The dashboard only shows on localhost with ?metrics=1 (or to a signed-in admin).
    await page.goto('/?metrics=1');
    await settle(page);
    await expect(page.locator('#skyview-conversion-dashboard')).toBeVisible();
    await page.waitForTimeout(600);
    await shot(page, 'local-dashboard');
  });
});

test.describe('client portal', () => {
  test('rate-limiting', async ({ page }) => {
    await page.addInitScript((lockedUntil) => {
      localStorage.setItem('skyview:portal-attempts:v1', JSON.stringify({ count: 5, lockedUntil }));
    }, NOW.getTime() + 15 * 60 * 1000);
    await page.goto('/pages/client-portal.html');
    await settle(page);
    await expect(page.getByRole('button', { name: 'Too many attempts' })).toBeDisabled();
    await shot(page, 'rate-limiting');
  });

  test('time-bound-token-expiry', async ({ page }) => {
    await page.goto('/pages/client-portal.html');
    await settle(page);
    const expired = Math.floor(NOW.getTime() / 1000) - 86400;
    await page.fill('#accessCode', `ZGVtby1jbGllbnQ.${expired}.${'0'.repeat(64)}`);
    await page.click('#submitBtn');
    await expect(page.locator('#errorMessage')).toHaveClass(/show/);
    await shot(page, 'time-bound-token-expiry');
  });

  test('token-generator', async ({ page }) => {
    // Real CLI output, with a throwaway salt and the clock pinned so the token is stable.
    const freeze = `data:text/javascript,Date.now=()=>${NOW.getTime()};`;
    const args = ['--import', freeze, 'scripts/portal-token.js', '--client', 'demo-wedding', '--days', '30'];
    const out = execFileSync(process.execPath, args, { cwd: repoRoot, env: { ...process.env, PORTAL_SALT: 'visual-docs-demo-salt' }, encoding: 'utf8' });
    const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
    await page.setViewportSize({ width: 1280, height: 520 });
    await page.setContent(`<!doctype html><body style="margin:0;background:#0b1120;color:#d7e3f4;font:15px/1.6 ui-monospace,Menlo,Consolas,monospace">
      <pre style="margin:0;padding:28px 32px;white-space:pre-wrap;word-break:break-all"><span style="color:#7cf2ff">$</span> PORTAL_SALT=&lt;secret&gt; node scripts/portal-token.js --client demo-wedding --days 30\n${esc(out)}</pre></body>`);
    await shot(page, 'token-generator');
  });
});

test.describe('admin', () => {
  test('decap-cms', async ({ page }) => {
    // Swap git-gateway for Decap's in-memory test backend so the editor opens without Netlify Identity.
    await page.route('**/admin/config.yml', async (route) => {
      const res = await route.fetch();
      const body = (await res.text()).replace('name: git-gateway', 'name: test-repo');
      await route.fulfill({ response: res, body });
    });
    await page.route('**/identity.netlify.com/**', (route) => route.abort());
    await page.goto('/admin/');
    await page.getByRole('button', { name: /login/i }).click();
    await expect(page.getByRole('heading', { name: /collections/i })).toBeVisible({ timeout: 30000 });
    await page.waitForTimeout(800);
    await shot(page, 'decap-cms');
  });
});

test.describe('marketplace platform', () => {
  const client = { id: 'client-1', role: 'client', name: 'Dana Whitfield', email: 'dana@example.com', active: true };
  const operator = {
    id: 'op-1', name: 'Harbor Aerial Co.', bio: 'Part 107 pilot flying waterfront listings, marinas and golden-hour reels since 2021.',
    avg_rating: 4.9, review_count: 38, service_types: ['real_estate', 'cinema', 'events'], base_rate_cents: 35000, coverage_radius_mi: 50,
  };
  const operators = [
    operator,
    { id: 'op-2', name: 'Ridgeline Survey', bio: 'Orthomosaic mapping, volumetrics and progress flights for builders.', avg_rating: 4.8, review_count: 21, service_types: ['mapping', 'inspection'], base_rate_cents: 48000 },
    { id: 'op-3', name: 'Lumen Flight Films', bio: 'FPV and cinema rigs for weddings, festivals and brand films.', avg_rating: 5, review_count: 12, service_types: ['cinema', 'events'], base_rate_cents: 60000 },
  ];
  const jobs = [
    { id: 'job-1', title: 'Waterfront listing shoot, 3BR', service_type: 'real_estate', status: 'open', preferred_date: '2027-02-01', preferred_time: 'morning', budget_cents: 40000 },
    { id: 'job-2', title: 'Marina grand-opening reel', service_type: 'events', status: 'matched', preferred_date: '2027-02-06', budget_cents: 75000 },
    { id: 'job-3', title: 'Lot 14 progress survey', service_type: 'mapping', status: 'booked', preferred_date: '2027-01-22', budget_cents: 52000 },
    { id: 'job-4', title: 'Rooftop inspection, Pier 9', service_type: 'inspection', status: 'completed', preferred_date: '2026-12-18', budget_cents: 30000 },
  ];
  const bookings = [{ id: 'bk-1', job_id: 'job-3', status: 'confirmed', operator_name: 'Ridgeline Survey' }];

  const mockApi = async (page: Page, me: object) => {
    await page.route('**/api/auth/me', (route) => route.fulfill(json(me)));
    await page.route('**/api/notifications*', (route) => route.fulfill(json({ unread_count: 2, notifications: [] })));
    await page.route('**/api/jobs', (route) => route.fulfill(json(jobs)));
    await page.route('**/api/bookings', (route) => route.fulfill(json(bookings)));
    await page.route('**/api/reviews*', (route) => route.fulfill(json([])));
    await page.route('**/api/operators*', (route) => route.fulfill(json(operators)));
    await page.route('**/api/operators/op-1', (route) => route.fulfill(json(operator)));
    await page.route('**/api/operators/op-1/availability', (route) => route.fulfill(json({
      weekly: [1, 2, 3, 4, 5].map((d) => ({ day_of_week: d, start_time: '09:00:00', end_time: '17:00:00' })),
      blocked: [{ blocked_date: '2027-02-02', reason: 'Maintenance' }],
    })));
    await page.route('**/nominatim.openstreetmap.org/**', (route) => route.fulfill(json([{ lat: '30.2672', lon: '-97.7431' }])));
  };

  test('two-sided-marketplace', async ({ page }) => {
    await mockApi(page, client);
    await page.goto(`${PLATFORM_BASE}/app/dashboard`);
    await expect(page.getByText('Lot 14 progress survey')).toBeVisible();
    await settle(page);
    await shot(page, 'two-sided-marketplace');

    await page.goto(`${PLATFORM_BASE}/app/operators`);
    await expect(page.getByText('Harbor Aerial Co.')).toBeVisible();
    await settle(page);
    await shot(page, 'two-sided-marketplace-operators');
  });

  test('two-sided-marketplace-post-job', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 1180 });
    await mockApi(page, client);
    await page.goto(`${PLATFORM_BASE}/app/jobs/new`);
    await page.getByText('Real Estate').click();
    await page.getByPlaceholder(/Real estate listing shoot/).fill('Waterfront listing shoot, 3BR');
    await page.getByPlaceholder(/Any specific requirements/).fill('Golden-hour exterior stills plus a 30-second reel. Dock access from the north gate.');
    await page.getByPlaceholder(/Street address or area/).fill('Downtown Austin, TX');
    await page.locator('input[type="date"]').fill('2027-02-01');
    await page.locator('.currency-input').fill('400');
    await page.locator('.currency-input').blur();
    await expect(page.getByText('Looking up coordinates')).toHaveCount(0);
    await settle(page);
    await shot(page, 'two-sided-marketplace-post-job');
  });

  test('native-operator-scheduling', async ({ page }) => {
    await mockApi(page, client);
    await page.goto(`${PLATFORM_BASE}/app/operators/op-1`);
    await page.getByRole('button', { name: 'Book This Operator' }).click();
    await expect(page.locator('select')).toBeVisible();
    await page.locator('select').selectOption('job-1');
    await expect(page.locator('input[type="date"]')).toHaveValue('2027-02-01');
    await expect(page.getByText("Within this operator's declared availability.")).toBeVisible();
    await page.locator('.currency-input').fill('400');
    await page.locator('.currency-input').blur();
    await settle(page);
    await page.waitForTimeout(600); // modal fade-in
    await shot(page, 'native-operator-scheduling');
  });

  test('native-operator-scheduling-availability', async ({ page }) => {
    await page.route('**/api/auth/me', (route) => route.fulfill(json({ id: 'op-1', role: 'operator', name: 'Harbor Aerial Co.', email: 'pilot@example.com', active: true, profile: { verification_status: 'verified' } })));
    await page.route('**/api/notifications*', (route) => route.fulfill(json({ unread_count: 0, notifications: [] })));
    // No profile row yet (first-time onboarding); saves succeed.
    await page.route('**/api/operators/op-1', (route) => route.fulfill(route.request().method() === 'GET' ? json({ error: 'not found' }, 404) : json({})));
    await page.route('**/api/operators/op-1/availability', (route) => route.fulfill(json({
      weekly: [1, 2, 3, 4, 5].map((d) => ({ day_of_week: d, start_time: '09:00:00', end_time: '17:00:00' })),
      blocked: [{ blocked_date: '2027-02-02', reason: 'Maintenance' }],
    })));
    await page.goto(`${PLATFORM_BASE}/app/operator/onboarding`);
    await page.getByText('Real Estate').click();
    await page.getByRole('button', { name: /next: rates/i }).click();
    await page.getByRole('button', { name: /next: availability/i }).click();
    await expect(page.getByLabel('Mon')).toBeChecked();
    await settle(page);
    await shot(page, 'native-operator-scheduling-availability');
  });
});
